services:
  timelapse-hw:
    image: gpocali/hw-timelapse-recorder:latest
    container_name: hw-timelapse-recorder
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    environment:
      - IMAGE_URL=http://your-camera-or-machine-ip/image.jpg
      - OUTPUT_FPS=30
      - FILE_PREFIX=cam1_timelapse
      - TZ=America/New_York
    volumes:
      - /path/to/your/local/output/folder:/output